### ISSUE TITLE
FR: Add a CSS class is-on-waitinglist

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-events_subscriptions#49]
Inside my list template I do a check if the logged in member is on the waiting list of actual event. Am I right that this has changed?
```php
<?php
// old
$waitingListCssClass = $this->subscribeWaitingList ? ' is-on-waitinglist' : ' ';
// new
$waitingListCssClass = $this->subscriptionTypes['member']['isOnWaitingList'] ? ' is-on-waitinglist' : ' ';
?>
```
Would be nice if the class for waitinglist gets genarated automatically
```html
<div id="event_1167" class="event layout current subscribed is-on-waitinglist odd last cal_2 " itemscope="" itemtype="http://schema.org/Event">
```

**Comment by qzminski** [comment]
It has not changed – the `subscribeWaitingList` variable indicates whether the next potential subscription would be to a waiting list, or not. If you want to add a new CSS class if a current member is already on the waiting list, then your "new" code is correct.

I would prefer not to add any CSS classes out of the box because:

1. not everyone needs them;
2. it would quickly clutter the markup as there are many potential features that could have their own CSS classes;
3. it would be hard to decide on the general naming scheme, as e.g. I prefer BEM but many people don't.

**Comment by Aybee** [comment]
Thank you. Never heard of BEM.

Nevertheless I will show you a screenshot so you can see how I like to use it. I changed the HTML manually from German to English and removed personal data for this screenshot. Not ready yet.

On the left you see the event list with subscription. I don't use a details page. In the right bar you see a booking list where a click on the links will scroll the page down to the equivalent event. The green and orange dots mark the events as registered or on the waiting list. Therefore I need this class. But since I have to adapt the templates anyway, I can also set up this class with PHP.

![Bildschirmfoto am 2020-08-04 um 21 13 20](https://user-images.githubusercontent.com/1143013/89336109-2b1eca80-d699-11ea-9d2b-1b9c76a33d37.png)

**Comment by qzminski** [comment]
I see your point but this is exactly the reason you have all those helper variables in the template. You can use them to format the markup properly, as well as add custom CSS classes tailored to your needs.

**Comment by Aybee** [comment]
Yes that is good. But I thought that especially for the events, where so many useful CSS classes already exist anyway, e.g. current, upcomming, bygone, subscribed etc. a class for the waiting list is simply missing out of the box.
